"use strict";

const friendsName = ["Saqalin", , "Murtaza", "Maisam"];
console.log(`${friendsName[1]} is a Freelancer`);
console.log(`${friendsName[2]} is a Martial Art`);
console.log(`${friendsName[3]} is a Business Man`);
console.log(`${friendsName[4]} is a Youtuber`);

//Undefined error

console.log("\nSolve undefined index error\n");
console.log(`${friendsName[0]} is a Freelancer`);
console.log(`${friendsName[1]} is a Martial Art`);
console.log(`${friendsName[2]} is a Business Man`);
console.log(`${friendsName[3]} is a Youtuber`);
